"use client";
import {useEffect,useState} from "react";
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,Legend} from "recharts";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:1}).format(n||0);
const pct=(n:any)=>n==null?"—":Number(n).toFixed(1)+"%"; const days=["D0","D1","D2","D3","D4"];
function Icon({type}:{type:string}){const p:any={app:"M4 4h16v16H4z M8 8h8M8 12h8M8 16h5",refresh:"M20 11a8 8 0 1 0 1 2",arrow:"M5 12h14m-6-6 6 6-6 6"};return <svg viewBox="0 0 24 24"><path d={p[type]||p.app}/></svg>}
function KPI({label,value,meta,danger=false}:{label:string;value:string;meta:string;danger?:boolean}){return <div className="kpi"><span>{label}</span><b className={danger?"danger":""}>{value}</b><small>{meta}</small></div>}
function SectionTitle({eyebrow,title,sub}:{eyebrow:string;title:string;sub:string}){return <div className="sectionTitle"><small>{eyebrow}</small><h2>{title}</h2><p>{sub}</p></div>}
function Status({value}:{value:string}){return <span className={"badge "+value.toLowerCase()}>{value}</span>}
export default function Dashboard(){const[d,setD]=useState<any>();const[err,setErr]=useState("");const[start,setStart]=useState("");const[end,setEnd]=useState("");const[loading,setLoading]=useState(false);const[selectedApp,setSelectedApp]=useState<string|null>(null);
const load=async()=>{try{setLoading(true);setErr("");const now=new Date(),e=end||now.toISOString().slice(0,10),s=start||new Date(now.getTime()-29*86400000).toISOString().slice(0,10);if(s>e)throw Error("From date cannot be after To date.");const r=await fetch("/api/dashboard?"+new URLSearchParams({start:s,end:e}),{cache:"no-store"});const j=await r.json();if(!r.ok)throw Error(j.error);setD(j);setStart(s);setEnd(e)}catch(e:any){setErr(e.message||"Unable to load dashboard")}finally{setLoading(false)}};useEffect(()=>{load()},[]);
if(err&&!d)return <div className="error"><b>Unable to load workspace</b><span>{err}</span><button onClick={load}>Retry</button></div>;if(!d)return <div className="error"><b>Loading Revenue Intelligence</b><span>Connecting to your database…</span></div>;const k=d.kpis;const jump=(id:string)=>{setSelectedApp(id);document.getElementById("app-"+id)?.scrollIntoView({behavior:"smooth",block:"start"})};
return <div className="app"><aside className="sidebar"><div className="brand"><div>IR</div><section><b>Invalid Revenue</b><small>REVENUE INTELLIGENCE</small></section></div><div className="sideHeading">YOUR APPS</div><nav>{d.apps.map((a:any)=><button key={a.id} className={selectedApp===String(a.id)?"active":""} onClick={()=>jump(String(a.id))}><span className="sideIcon"><Icon type="app"/></span><span className="appName">{a.name}</span><span className="appLoss">{money(a.loss)}</span></button>)}</nav><div className="sideFoot">● Live revenue workspace</div></aside>
<main><header><div className="crumb"><b>Revenue Intelligence</b><span>·</span>{d.apps.length} apps</div><button className="refresh" onClick={load}><Icon type="refresh"/>{loading?"Refreshing…":"Refresh Data"}</button></header><div className="page"><div className="head"><small>PORTFOLIO OVERVIEW</small><h1>Revenue at a glance</h1><p>One view of every app, every revenue date and every D0–D4 snapshot.</p></div>
<div className="filters"><div className="filterTitle"><small>REVENUE DATE</small><b>Filter the report date only</b></div><label>From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>To<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><button onClick={load} disabled={loading}>{loading?"Applying…":"Apply"}</button></div>
<div className="kpis"><KPI label="Initial Revenue" value={money(k.initial)} meta="D0 revenue"/><KPI label="Latest Revenue" value={money(k.latest)} meta="Latest available snapshot"/><KPI label="Revenue at Risk" value={money(k.risk)} meta="Initial − latest" danger/><KPI label="Adjustment Rate" value={pct(k.rate)} meta="Risk / initial" danger/><KPI label="Apps with Risk" value={String(k.affectedApps)} meta={"of "+d.apps.length}/><KPI label="Ad Units with Risk" value={String(k.affectedAdUnits)} meta="Selected revenue dates"/></div>
<section className="panel trendPanel"><SectionTitle eyebrow="PORTFOLIO TREND" title="Revenue by revenue date" sub="Report date is the horizontal axis; D0–D4 are separate revenue lines."/><div className="chart trendChart"><ResponsiveContainer width="100%" height="100%"><LineChart data={d.trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tickFormatter={v=>String(v).slice(5)}/><YAxis tickFormatter={v=>money(Number(v))}/><Tooltip labelFormatter={v=>"Revenue date: "+v} formatter={(v:any,n:any)=>[money(Number(v)),n]}/><Legend/><Line dataKey="d0" name="D0" stroke="var(--lineD0)" strokeWidth={2.5} dot={false} connectNulls/><Line dataKey="d1" name="D1" stroke="var(--lineD1)" strokeWidth={2.5} dot={false} connectNulls/><Line dataKey="d2" name="D2" stroke="var(--lineD2)" strokeWidth={2.5} dot={false} connectNulls/><Line dataKey="d3" name="D3" stroke="var(--lineD3)" strokeWidth={2.5} dot={false} connectNulls/><Line dataKey="d4" name="D4" stroke="var(--lineD4)" strokeWidth={2.5} dot={false} connectNulls/></LineChart></ResponsiveContainer></div></section>
<div className="appsHeader"><div><small>APP-BY-APP INTELLIGENCE</small><h2>Complete revenue picture</h2><p>Each app card contains only that app's D0–D4 revenue and ad units.</p></div><span>{d.apps.length} apps</span></div>
<div className="appList">{d.apps.map((a:any)=><AppCard key={a.id} app={a} adUnits={d.adUnits.filter((x:any)=>String(x.app_id)===String(a.id))} totals={d.appDayTotals[String(a.id)]||{}} adDaily={d.adDaily||{}} id={"app-"+a.id}/>)}</div>
</div></main></div>}
function AppCard({app,adUnits,totals,adDaily,id}:{app:any;adUnits:any[];totals:any;adDaily:any;id:string}){const values=days.map((x,i)=>totals["d"+i]??null);return <section className="appCard" id={id}><div className="appCardTop"><div className="appIdentity"><div className="appIcon"><Icon type="app"/></div><div><small>APPLICATION</small><h3>{app.name}</h3><span>Only this app's revenue data</span></div></div><div className="appHeadline"><span>Revenue at risk</span><b>{money(app.loss)}</b><Status value={app.status}/></div></div>
<div className="journey">{values.map((v,i)=><div className="journeyStep" key={days[i]}><div className="journeyLabel">{days[i]}</div><strong>{v==null?"—":money(v)}</strong><small>{v==null?"No snapshot":i===0?"Baseline":values[0]?((v/values[0])*100).toFixed(1)+"% retained vs D0":"—"}</small>{i<4&&<div className="flowArrow"><Icon type="arrow"/></div>}</div>)}</div>
<div className="appSummary"><div><span>Initial</span><b>{money(app.initial)}</b></div><div><span>Latest</span><b>{money(app.latest)}</b></div><div><span>Adjustment</span><b className={app.loss>0?"danger":""}>{pct(app.rate)}</b></div></div>
<div className="adBlock"><div className="adBlockHead"><b>Ad units for {app.name}</b><span>{adUnits.length}</span></div>{adUnits.length?<div className="adTableWrap"><table className="adTable"><thead><tr><th>Date</th><th>Ad Unit Name</th>{days.map(x=><th key={x}>{x} Revenue</th>)}</tr></thead><tbody>{adUnits.flatMap((ad:any)=>Object.keys(adDaily[String(ad.id)]||{}).sort().map(date=><tr key={ad.id+"-"+date}><td>{date}</td><td><b>{ad.name}</b></td>{days.map((x:any,i:number)=><td key={x}>{adDaily[String(ad.id)]?.[date]?.["d"+i]==null?"—":money(adDaily[String(ad.id)][date]["d"+i])}</td>)}</tr>))}</tbody></table></div>:<div className="empty">No ad-unit revenue in this period.</div>}</div></section>}
