"use client";
import {useEffect,useState} from "react";
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,BarChart,Bar} from "recharts";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n||0);
const pct=(n:any)=>n==null?"N/A":Number(n).toFixed(1)+"%";
const nav=[{id:"overview",label:"Overview",icon:"⌂"},{id:"revenue",label:"Revenue",icon:"◈"},{id:"apps",label:"Apps",icon:"▦"},{id:"adunits",label:"Ad Units",icon:"▤"},{id:"adjustments",label:"Adjustments",icon:"↗"},{id:"alerts",label:"Alerts",icon:"!"},{id:"health",label:"Data Health",icon:"✓"}];
function KPI({label,value,meta,negative=false}:{label:string,value:string,meta:string,negative?:boolean}){return <div className="kpi"><div className="kpiTop"><span>{label}</span><span className="kpiIcon">↗</span></div><strong>{value}</strong><small className={negative?"negative":""}>{meta}</small></div>}
function SectionTitle({eyebrow,title,sub}:{eyebrow:string,title:string,sub:string}){return <div className="sectionTitle"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{sub}</p></div></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
export default function Dashboard(){
 const [d,setD]=useState<any>(null),[err,setErr]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[app,setApp]=useState("all"),[platform,setPlatform]=useState("all"),[entity,setEntity]=useState("all"),[ad,setAd]=useState("all"),[metric,setMetric]=useState("latest"),[section,setSection]=useState("overview"),[mobileOpen,setMobileOpen]=useState(false),[loading,setLoading]=useState(false);
 const load=async()=>{try{setLoading(true);setErr("");const now=new Date(),e=end||now.toISOString().slice(0,10),s=start||new Date(now.getTime()-29*86400000).toISOString().slice(0,10);const q=new URLSearchParams({start:s,end:e,app,platform,entityType:entity,adUnit:ad});const r=await fetch("/api/dashboard?"+q);const j=await r.json();if(!r.ok)throw Error(j.error||"Unable to load dashboard");setD(j);setStart(s);setEnd(e)}catch(x:any){setErr(x.message||"Unable to load dashboard")}finally{setLoading(false)}};
 useEffect(()=>{load()},[app,platform,entity,ad]);
 if(err&&!d)return <main className="app"><div className="loading"><b>Unable to load workspace</b><span>{err}</span><button className="primary" onClick={load}>Retry</button></div></main>;
 if(!d)return <main className="app"><div className="loading"><b>Loading Revenue Intelligence</b><span>Preparing your financial workspace…</span></div></main>;
 const k=d.kpis;const chart=d.trend.map((r:any)=>({date:r.date,value:metric==="initial"?r.d0:Math.max(r.d0||0,r.d1||0,r.d2||0,r.d3||0,r.d4||0)}));
 const go=(id:string)=>{setSection(id);setMobileOpen(false);window.scrollTo({top:0,behavior:"smooth"})};const title=nav.find(x=>x.id===section)?.label||"Overview";
 return <main className="app"><aside className={"sidebar "+(mobileOpen?"open":"")}>
  <div className="brand"><div className="brandMark">IR</div><div><b>Invalid Revenue</b><span>INTELLIGENCE</span></div></div>
  <div className="workspace"><span className="liveDot"/> Executive Workspace <span>⌄</span></div>
  <nav>{nav.map(x=><button key={x.id} className={section===x.id?"navItem active":"navItem"} onClick={()=>go(x.id)}><i>{x.icon}</i><span>{x.label}</span>{x.id==="alerts"&&d.attention.length>0?<em>{d.attention.length}</em>:null}</button>)}</nav>
  <div className="sidebarBottom"><button onClick={()=>go("health")}>⚙ Settings</button><div className="profile"><div className="avatar">AI</div><div><b>Analytics Workspace</b><span>Revenue Operations</span></div><span>•••</span></div></div>
 </aside>
 <section className="main"><header className="topbar"><button className="mobileMenu" onClick={()=>setMobileOpen(!mobileOpen)}>☰</button><div className="crumb">Revenue Intelligence <span>/</span> <b>{title}</b></div><div className="topActions"><span className="statusPill"><i/> Data connected</span><button className="iconBtn" title="Refresh" onClick={load}>↻</button><button className="avatarSmall">AI</button></div></header>
 <div className="page"><div className="pageHeader"><div><span className="eyebrow">EXECUTIVE CONTROL CENTER</span><h1>{title}</h1><p>{section==="overview"?"Monitor invalid revenue exposure, adjustments and recovery signals across your portfolio.":"Focused intelligence for "+title.toLowerCase()+"."}</p></div><button className="primary" onClick={load}>{loading?"Refreshing…":"↻ Refresh data"}</button></div>
 <div className="filterBar"><div className="filterLabel">ANALYSIS PERIOD</div><label><span>From</span><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label><span>To</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label><span>App</span><select value={app} onChange={e=>setApp(e.target.value)}><option value="all">All Apps</option>{d.filters.apps.map((x:any)=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label><span>Platform</span><select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="all">All Platforms</option>{d.filters.platforms.map((x:string)=><option key={x}>{x}</option>)}</select></label><button className="filterApply" onClick={load}>Apply</button></div>
 {section==="overview"&&<><div className="hero"><div><span>PORTFOLIO SIGNAL</span><h2>{k.revenueAtRisk>0?"Revenue exposure requires attention":"Portfolio is currently stable"}</h2><p>{d.summary}</p></div><div className="heroMetric"><small>REVENUE AT RISK</small><strong>{money(k.revenueAtRisk)}</strong><span>{k.adjustmentRate==null?"No adjustment signal":pct(k.adjustmentRate)+" adjustment rate"}</span></div></div>
 <div className="kpis"><KPI label="Initial invalid revenue" value={money(k.initial)} meta="Baseline detected revenue"/><KPI label="Latest invalid revenue" value={money(k.latest)} meta="Latest available snapshot"/><KPI label="Revenue at risk" value={money(k.revenueAtRisk)} meta="Potential exposure" negative={k.revenueAtRisk>0}/><KPI label="Total adjustment" value={money(k.adjustment)} meta="Recorded adjustments" negative={k.adjustment>0}/><KPI label="Adjustment rate" value={k.adjustmentRate==null?"N/A":pct(k.adjustmentRate)} meta="Against initial revenue"/><KPI label="Affected entities" value={String((k.affectedApps||0)+(k.affectedAdUnits||0))} meta={(k.affectedApps||0)+" apps · "+(k.affectedAdUnits||0)+" ad units"}/></div>
 <div className="twoCol"><section className="panel chartPanel"><div className="panelHead"><div><span className="eyebrow">EXPOSURE</span><h3>Invalid revenue trend</h3><p>Daily revenue snapshots across the selected period</p></div><select value={metric} onChange={e=>setMetric(e.target.value)}><option value="latest">Latest available</option><option value="initial">Initial (D0)</option></select></div><div className="chart"><ResponsiveContainer width="100%" height={310}><LineChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Line type="monotone" dataKey="value" stroke="#111827" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div></section>
 <section className="panel"><div className="panelHead"><div><span className="eyebrow">RECOVERY</span><h3>Revenue retention</h3><p>Post-detection revenue by snapshot day</p></div></div><div className="retention">{d.retention.map((x:any)=><div className="ret" key={x.snapshot_day}><div><b>D{x.snapshot_day}</b><span>Snapshot</span></div><strong>{pct(x.retention)}</strong><div className="retBar"><i style={{width:(x.retention==null?0:Math.min(100,x.retention))+"%"}}/></div></div>)}</div><div className="retHero"><span>D4 retention</span><b>{pct(d.retention.find((x:any)=>x.snapshot_day===4)?.retention)}</b></div></section></div>
 <div className="twoCol"><section className="panel"><SectionTitle eyebrow="EXCEPTIONS" title="CEO attention required" sub="Highest-severity financial signals"/>{d.attention.length?d.attention.map((x:any)=><div className="exception" key={x.type+x.id}><span className={"severity "+x.status.toLowerCase()}/><div><b>{x.name}</b><small>{x.type} · {money(x.adjustment)} adjustment · {pct(x.adjustment_pct)}</small></div><strong>{x.status}</strong></div>):<Empty text="No high-priority exceptions found."/>}</section><section className="panel"><SectionTitle eyebrow="IMPACT" title="Top apps by adjustment" sub="Largest financial adjustments first"/><div className="chart mini"><ResponsiveContainer width="100%" height={280}><BarChart data={d.apps.slice(0,8).map((x:any)=>({name:x.name.length>16?x.name.slice(0,16)+"…":x.name,value:Math.abs(Number(x.adjustment))}))} layout="vertical"><XAxis type="number" hide/><YAxis type="category" dataKey="name" width={105} tick={{fontSize:10}}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar dataKey="value" fill="#111827" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div></section></div></>}
 {section==="revenue"&&<><SectionTitle eyebrow="REVENUE INTELLIGENCE" title="Revenue exposure & recovery" sub="Understand how invalid revenue changes from initial detection through later snapshots."/><div className="kpis"><KPI label="Initial revenue" value={money(k.initial)} meta="D0 baseline"/><KPI label="Latest revenue" value={money(k.latest)} meta="Latest snapshot"/><KPI label="At risk" value={money(k.revenueAtRisk)} meta="Initial less latest" negative/><KPI label="Adjustment rate" value={pct(k.adjustmentRate)} meta="Portfolio rate"/></div><section className="panel chartPanel"><div className="panelHead"><div><h3>Revenue timeline</h3><p>Use the selector to compare initial and latest available revenue.</p></div><select value={metric} onChange={e=>setMetric(e.target.value)}><option value="latest">Latest available</option><option value="initial">Initial (D0)</option></select></div><div className="chart tall"><ResponsiveContainer width="100%" height={420}><LineChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip formatter={(v:any)=>money(Number(v))}/><Line type="monotone" dataKey="value" stroke="#111827" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div></section></>}
 {section==="apps"&&<><SectionTitle eyebrow="PORTFOLIO" title="Apps" sub="Financial impact across application entities."/><section className="panel"><div className="tableWrap"><table><thead><tr><th>Application</th><th>Platform</th><th>Initial</th><th>Latest</th><th>Loss</th><th>Adjustment</th><th>Rate</th><th>Status</th></tr></thead><tbody>{d.apps.map((x:any)=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.platform||"—"}</td><td>{money(x.initial)}</td><td>{money(x.latest)}</td><td>{money(x.loss)}</td><td>{money(x.adjustment)}</td><td>{pct(x.adjustment_pct)}</td><td><span className={"badge "+x.status.toLowerCase()}>{x.status}</span></td></tr>)}</tbody></table></div></section></>}
 {section==="adunits"&&<><SectionTitle eyebrow="MONETIZATION" title="Ad Units" sub="Identify ad units driving the highest invalid-revenue impact."/><section className="panel"><div className="tableWrap"><table><thead><tr><th>Ad Unit</th><th>Platform</th><th>Initial</th><th>Latest</th><th>Loss</th><th>Adjustment</th><th>Rate</th><th>Status</th></tr></thead><tbody>{d.adUnits.map((x:any)=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.platform||"—"}</td><td>{money(x.initial)}</td><td>{money(x.latest)}</td><td>{money(x.loss)}</td><td>{money(x.adjustment)}</td><td>{pct(x.adjustment_pct)}</td><td><span className={"badge "+x.status.toLowerCase()}>{x.status}</span></td></tr>)}</tbody></table></div></section></>}
 {section==="adjustments"&&<><SectionTitle eyebrow="FINANCIAL CONTROL" title="Adjustments" sub="Portfolio-level adjustment intelligence and exposure."/><div className="kpis"><KPI label="Total adjustments" value={money(Number(d.adjustmentIntelligence.total||0))} meta="Selected period"/><KPI label="Average rate" value={pct(d.adjustmentIntelligence.avg)} meta="Mean adjustment %"/><KPI label="Median rate" value={pct(d.adjustmentIntelligence.median)} meta="Median adjustment %"/><KPI label="Largest adjustment" value={money(Number(d.adjustmentIntelligence.largest||0))} meta="Single entity"/></div><section className="panel"><SectionTitle eyebrow="RANKING" title="Apps by financial impact" sub="Largest adjustments first"/><div className="tableWrap"><table><thead><tr><th>Application</th><th>Adjustment</th><th>Adjustment rate</th><th>Loss</th><th>Status</th></tr></thead><tbody>{d.apps.slice(0,25).map((x:any)=><tr key={x.id}><td><b>{x.name}</b></td><td>{money(x.adjustment)}</td><td>{pct(x.adjustment_pct)}</td><td>{money(x.loss)}</td><td><span className={"badge "+x.status.toLowerCase()}>{x.status}</span></td></tr>)}</tbody></table></div></section></>}
 {section==="alerts"&&<><SectionTitle eyebrow="RISK MONITOR" title="Alerts" sub="Critical exceptions requiring executive attention."/><section className="panel alertPanel">{d.attention.length?d.attention.map((x:any)=><div className="alertRow" key={x.type+x.id}><div className="alertIcon">!</div><div><b>{x.name}</b><p>{x.type} has a {pct(x.adjustment_pct)} adjustment impact.</p></div><strong>{money(x.adjustment)}</strong><span className="badge critical">{x.status}</span></div>):<Empty text="All monitored entities are below the critical threshold."/>}</section></>}
 {section==="health"&&<><SectionTitle eyebrow="PIPELINE" title="Data Health" sub="Monitor ingestion freshness, processing quality and failures."/><section className="panel"><div className="healthSummary"><div><span>CONNECTION</span><b><i/> Operational</b></div><div><span>RECENT RUNS</span><b>{d.dataHealth.length}</b></div><div><span>FAILURES</span><b>{d.dataHealth.reduce((n:number,x:any)=>n+Number(x.records_failed||0),0)}</b></div></div>{d.dataHealth.length?d.dataHealth.map((x:any,i:number)=><div className="run" key={i}><span className={"healthDot "+String(x.status).toLowerCase()}/><div><b>{x.workflow_name||x.source||"Ingestion"}</b><small>{x.source||"Data pipeline"}</small></div><strong>{x.status}</strong><span>{x.records_received??0} received · {x.records_processed??0} processed · {x.records_failed??0} failed</span><time>{x.completed_at?new Date(x.completed_at).toLocaleString():"Unavailable"}</time></div>):<Empty text="No ingestion runs are available."/>}</section></>}
 </div></section></main>
}